name = "rentflow"
compatibility_date = "2026-06-12"
pages_build_output_dir = "out"

[[r2_buckets]]
binding = "RENTFLOW_UPLOADS"
bucket_name = "rentflow-uploads"

[[d1_databases]]
binding = "DB"
database_name = "rentflow_db"
database_id = "84b87775-99a2-453e-8513-106775886f14" # Placeholder, user will need to update with real ID if needed for production

